### ISSUE TITLE
setScopedState({}) is a no-op

### ISSUE THREAD

**Issue by franky47** [reasv/panoptikon-ui#1]
https://github.com/reasv/panoptikon-ui/blob/fe894b75e8e4c1cdf092b71ba6320ea4ded98545/lib/state/nuqsScopedWrappers/scopedQueryStates.ts#L153

This will not do anything, as the state updater function accepts a partial object of values, and anything **not** in that object will be left as-is.

To clear all keys managed by a `useQueryStates` hook, since `nuqs@1.19.1`, you can pass `null` as an argument:

```tsx
setScopedState(null)
```

**Comment by franky47** [comment]
@afreisz is a malicious account / spam, @reasv please delete & report.

**Comment by reasv** [comment]
Thanks, I am aware that this is the case.
Notice that I added these lines yesterday evening when updating to 1.19.1.
Look at the line of code above, it calls set(null).
The line below with {} was a no-op I had added to keep the return type
valid and consistent before the change.

**Comment by franky47** [comment]
My bad, I misread the line above, looks good!

**Comment by reasv** [comment]
Thanks for taking a look regardless!

**Comment by franky47** [comment]
That's quite the impressive data plumbing! Feel free to post about it on the [Show & Tell](https://github.com/47ng/nuqs/discussions/categories/show-and-tell) section of the nuqs discussions.
